# Generated by Django 5.0.4 on 2024-12-07 00:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviatorgame',
            name='round_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
